# Generated by Django 3.1.7 on 2021-03-31 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('from_email', models.EmailField(default=None, max_length=254, verbose_name='Người gửi')),
                ('to_email', models.EmailField(default=None, max_length=254, verbose_name='Người nhận')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('sent_date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày gửi')),
                ('state', models.IntegerField(blank=True, choices=[(0, 'Chưa gửi'), (1, 'Gửi thành công'), (2, 'Gửi thất bại')], default=0, null=True, verbose_name='Trạng thái')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Email',
                'db_table': 'email_inbox',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('to_user_id', models.IntegerField(default=None, verbose_name='Mã người nhận')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('url', models.CharField(max_length=255, verbose_name='Url')),
                ('sent_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ngày gửi')),
                ('viewed_state', models.BooleanField(default=False, editable=False, verbose_name='Đã đọc')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'db_table': 'notification',
                'ordering': ['viewed_state'],
                'managed': True,
            },
        ),
    ]
