"""
Django settings for app_config project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c=huvrktm!r^*n$@2_-nn144ht0l!3(fk@0s9qwxznlw3rhvz0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "PlusPlus Academy",
    "site_bar_title": "PlusPlus Language",
    # Title on the brand, and the login screen (19 chars max)
    "site_header": "PlusPlus Academy",
    # Welcome text on the login screen
    "welcome_sign": "",
    "site_logo": "assets/plusplus_logo.png",
    # Copyright on the footer
    "copyright": "PlusPlus Academy",

    # The model admin to search from the search bar, search bar omitted if excluded
    # "search_model": "auth.User",
    "custom_css": "css/styles.css",
    "custom_js": "js/custom.js",
    "icons": {
        "auth": "fas fa-key",
        "auth.Permission": "fas fa-address-book",
        "auth.Group": "fas fa-users",
        "user.AuthUser": "fas fa-user",
        "user.StudentCare": "fas fa-people-arrows",
        "user.Receptionist": "fas fa-users-cog",
        "user.BusinessEmployee": "fas fa-user-tie",
        "user.Teacher": "fas fa-chalkboard-teacher",
        "user.Student": "fas fa-user-graduate",
        "user.Tests": "fas fa-file-alt",
        "user.Commendation": "fas fa-award",
        "centre.ClassRoom": "fas fa-store-alt",
        "centre.Centre": "fas fa-synagogue",
        "centre.Course": "fas fa-clipboard-list",
        "centre.Classes": "fas fa-archway",
        "centre.StudyShift": "fas fa-calendar",
        "centre.StudyShiftSchedule": "far fa-calendar-alt",
        "centre.Tasks": "fas fa-tasks",
        "centre.Issues": "fab fa-intercom",
        "message.EmailInbox": "fas fa-envelope-open-text",
        "message.Notification": "fas fa-bell",
        "finance.StudentSendPaymentRequest": "fas fa-dollar-sign",
        "finance.StudentDebt": "fas fa-file-invoice-dollar",
        "finance.StudentDebtView": "fas fa-user-times",
        "finance.Reward": "fas fa-gift",
        "finance.StudentReceiveReward": "fas fa-hand-holding-usd",
        "assessment.AssessmentCategory": "fas fa-tasks",
        "admin.LogEntry": "fas fa-history",
    },
    # Icons that are used when one is not manually specified
    # "default_icon_parents": "fas fa-chevron-circle-right",
    # "default_icon_children": "fas fa-circle",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,

    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": False,
    "notification": True,

    ###############
    # Change view #
    ###############
    # Render out the change view as a single form, or in tabs, current options are
    # - single
    # - horizontal_tabs (default)
    # - vertical_tabs
    # - collapsible
    # - carousel
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs",
                                    "finance.StudentDebt": "single"},
    # Add a language dropdown into the admin
    "language_chooser": False,

    #############
    # Side Menu #
    #############

    # Whether to display the side menu
    "show_sidebar": True,

    # Whether to aut expand the menu
    "navigation_expanded": True,

    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": ['fcm_django'],

    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": ['finance.Revenue'],

    "order_with_respect_to": [
        "centre"
        , "centre.Centre"
        , "centre.ClassRoom"
        , "centre.Course"
        , "centre.Classes"
        , "centre.StudyShift"
        , "user", "user.Authuser", 'user.StudentCare', 'user.Receptionist', 'user.BusinessEmployee'
        , 'user.Teacher', 'user.Student'
        , "user.Tests", "user.Commendation"
        , "manager"
        , "message"
        , "finance"
        , "auth"
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'django.contrib.admin',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.auth',
    'manager.apps.ManagersConfig',
    'message.apps.MessageConfig',
    'finance.apps.FinanceConfig',
    'centre.apps.CentreConfig',
    'user.apps.UserConfig',
    'history.apps.HistoryConfig',
    'assessment.apps.AssessmentConfig',
    # 'daterangefilter',
    'rangefilter',
    'csp',
    'rest_framework',
    'fcm_django',
    'corsheaders',
    'sslserver',
    'chartjs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

ROOT_URLCONF = 'app_config.urls'
# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app_config.wsgi.application'
AUTH_USER_MODEL = 'user.AuthUser'
# X_FRAME_OPTIONS = 'ALLOW-FROM http://odinlanguage.com/'
# CSRF_COOKIE_SECURE = False
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = False
# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mc_ecm_test',
        'USER': 'root',
        'PASSWORD': 'medusa1998',
        'HOST': 'localhost',
        'PORT': '3306',
    }

    # 'default': {
    #         'ENGINE': 'django.db.backends.mysql',
    #         'NAME': 'mc_ecm',
    #         'USER': 'mcuser',
    #         'PASSWORD': 'mcuser',
    #         'HOST': 'localhost',
    #         'PORT': '3306',
    # }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# MAIL HOST INFO:
email_address = os.environ.get("EMAIL_ADDRESS", default='ODIN Language Academy <noreply@odinlanguage.com>')
email_password = os.environ.get("EMAIL_PASSWORD", default='[E?JXa6F8XSD')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'pro17.emailserver.vn'
EMAIL_HOST_USER = 'noreply@odinlanguage.com'
EMAIL_HOST_PASSWORD = '[E?JXa6F8XSD'
EMAIL_USE_TLS = True
EMAIL_PORT = 587

# FCM Django settings
FCM_DJANGO_SETTINGS = {
        "FCM_SERVER_KEY": "AAAAUBWqdfo:APA91bEm3ib6_TlLIJ5YpAU6BjyQ7X9GoXeghkgqiBwNPPkr_FP9NjdhVk8EZqCUvgWUIf2vhk5eUnSkJELy7JtJfv1qOGM_UZtxu0FI3BkpUQMxdX-aO3xdvfTKteAkbAc2vXy1xCXu"
}

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
X_FRAME_OPTIONS = 'SAMEORIGIN'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication',
    ),
}

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_L10N = False

USE_TZ = False

DATE_INPUT_FORMATS = ['%d/%m/%Y']
DEFAULT_DATE_FORMAT = "%d/%m/%Y"
DEFAULT_DATE_TIME_FORMAT = "%d/%m/%Y %H:%M:%S"
USE_THOUSAND_SEPARATOR = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

BOOTSTRAP4 = {
    'include_jquery': True,
}

LOGIN_REDIRECT_URL = '/admin/'
LOGOUT_REDIRECT_URL = "/admin/login/"
