# Generated by Django 3.1.7 on 2021-03-31 09:47

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền')),
                ('payment_method', models.IntegerField(blank=True, choices=[(0, 'Tiền mặt'), (1, 'Tech'), (2, 'MB'), (3, 'BIDV')], default=None, null=True, verbose_name='Tài khoản nộp')),
                ('completed_pay_date', models.DateField(default=datetime.datetime(2021, 3, 31, 9, 47, 41, 123018), verbose_name='Ngày nộp')),
            ],
            options={
                'verbose_name': 'Thanh toán công nợ',
                'verbose_name_plural': 'Thanh toán công nợ',
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền (VNĐ)')),
                ('input_date', models.DateField(default=None, verbose_name='Ngày thu')),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ghi chú')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Doanh thu',
                'verbose_name_plural': 'Doanh thu',
                'db_table': 'revenues',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='Mã ưu đãi')),
                ('type', models.IntegerField(choices=[(1, 'Giảm giá'), (2, 'Quà tặng')], default=1, verbose_name='Loại ưu đãi')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số lượng')),
                ('gift', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quà tặng')),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giảm giá (%)')),
                ('start_date', models.DateField(default=datetime.date(2021, 3, 31), verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(default=datetime.date(2021, 4, 30), verbose_name='Ngày kết thúc')),
            ],
            options={
                'verbose_name': 'Ưu đãi',
                'verbose_name_plural': 'Ưu đãi',
                'db_table': 'reward',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255, verbose_name='Ghi chú')),
                ('student_level', models.IntegerField(blank=True, choices=[(1, 'BB'), (2, 'C'), (3, 'IE1'), (4, 'IE2'), (5, 'IE3'), (6, 'TO1'), (7, 'TO2')], default=None, null=True, verbose_name='Trình độ hiện tại')),
                ('study_schedule_select', models.IntegerField(choices=[(1, 'Ca 1 (9h-10h30)'), (2, 'Ca 2 (14h-15h30)'), (3, 'Ca 3 (18h-19h30)'), (4, 'Ca 4 (19h30-21h)')], default=1, verbose_name='Ca học')),
                ('origin_amount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Giá')),
                ('discount_percent', models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Giảm giá(%)')),
                ('plan_date', models.DateField(default=None, verbose_name='Ngày hẹn hoàn thành')),
                ('rest_amount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền còn nợ')),
                ('back_amount', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền hoàn lại')),
                ('back_reason', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Lý do hoàn lại')),
                ('completed_pay_date', models.DateField(blank=True, null=True, verbose_name='Ngày hoàn thành')),
                ('gift', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Quà tặng')),
                ('consultant', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Tư vấn viên')),
                ('contract', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Hợp đồng')),
                ('receipt', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Hóa đơn')),
                ('contract_state', models.IntegerField(blank=True, choices=[(1, 'Cam kết'), (2, 'Mất cam kết'), (3, 'Cảnh cáo'), (4, 'Thanh lý hợp đồng')], default=None, null=True, verbose_name='Tình trạng hợp đồng')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('centre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm')),
            ],
            options={
                'verbose_name': 'Doanh thu',
                'verbose_name_plural': 'Doanh thu',
                'db_table': 'student_debt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentDebtView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'HV đến hạn nộp tiền',
                'verbose_name_plural': 'HV đến hạn nộp tiền',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentSendPaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mã giao dịch')),
                ('full_name', models.CharField(default=None, max_length=150, verbose_name='Tên sinh viên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ.', regex='^\\+?(?:0|84)(?:\\d){9}$')], verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('study_schedule_select', models.IntegerField(choices=[(1, 'Ca 1 (9h-10h30)'), (2, 'Ca 2 (14h-15h30)'), (3, 'Ca 3 (18h-19h30)'), (4, 'Ca 4 (19h30-21h)')], default=1, verbose_name='Ca học')),
                ('must_pay_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền phải nộp')),
                ('paid_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Số tiền nộp')),
                ('payment_method', models.IntegerField(blank=True, choices=[(0, 'Tiền mặt'), (1, 'Tech'), (2, 'MB'), (3, 'BIDV')], default=None, null=True, verbose_name='Tài khoản nộp')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'Đồng ý'), (2, 'Chờ HV'), (3, 'Từ chối')], default=None, null=True, verbose_name='Trạng thái')),
                ('send_date', models.DateField(default=datetime.datetime(2021, 3, 31, 9, 47, 41, 124889), verbose_name='Ngày nộp')),
                ('plan_complete_date', models.DateField(blank=True, default=None, null=True, verbose_name='Ngày hen hoan thanh')),
                ('student_level', models.IntegerField(blank=True, choices=[(1, 'BB'), (2, 'C'), (3, 'IE1'), (4, 'IE2'), (5, 'IE3'), (6, 'TO1'), (7, 'TO2')], default=None, null=True, verbose_name='Trình độ hiện tại')),
                ('free_day_in_week', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lịch rảnh')),
                ('centre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm')),
                ('classes', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.course', verbose_name='Khóa học')),
                ('reward', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.reward', verbose_name='Ưu đãi')),
                ('student_debt', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.studentdebt')),
            ],
            options={
                'verbose_name': 'Thanh toán học phí',
                'verbose_name_plural': 'Thanh toán học phí',
                'db_table': 'student_send_request_payment',
                'managed': True,
            },
        ),
    ]
