# Generated by Django 3.1.7 on 2021-03-31 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('centre', '0002_auto_20210331_0947'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdebt',
            name='collector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collector_set', to=settings.AUTH_USER_MODEL, verbose_name='Người thu'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='counselor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counselor_set', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên kinh doanh'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studentdebt_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='reward',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.reward', verbose_name='Ưu đãi'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.student', verbose_name='Học viên'),
        ),
        migrations.AddField(
            model_name='studentdebt',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='studentdebt_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='reward',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, help_text='Nếu không trọn khoá học nào, ưu đãi sẽ được áp dụng cho tất cả các khoá học.<br>', null=True, to='centre.Course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='centre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revenue_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='revenue',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người nộp'),
        ),
        migrations.AddField(
            model_name='payment',
            name='student_debt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.studentdebt', verbose_name='Công nợ'),
        ),
    ]
