# Generated by Django 3.1.7 on 2021-03-31 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20210331_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completed_pay_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 10, 12, 32, 790079), verbose_name='Ngày nộp'),
        ),
        migrations.AlterField(
            model_name='studentsendpaymentrequest',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 10, 12, 32, 791884), verbose_name='Ngày nộp'),
        ),
    ]
