# Generated by Django 3.1.4 on 2021-04-06 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20210331_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completed_pay_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 10, 14, 22, 362439), verbose_name='Ngày nộp'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='end_date',
            field=models.DateField(default=datetime.date(2021, 5, 6), verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='start_date',
            field=models.DateField(default=datetime.date(2021, 4, 6), verbose_name='Ngày bắt đầu'),
        ),
        migrations.AlterField(
            model_name='studentsendpaymentrequest',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 10, 14, 22, 363667), verbose_name='Ngày nộp'),
        ),
    ]
