# Generated by Django 3.1.4 on 2021-04-06 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_auto_20210406_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='completed_pay_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 11, 36, 3, 727039), verbose_name='Ngày nộp'),
        ),
        migrations.AlterField(
            model_name='studentsendpaymentrequest',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 11, 36, 3, 727899), verbose_name='Ngày nộp'),
        ),
    ]
