# Generated by Django 3.1.7 on 2021-03-31 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        ('finance', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyshiftteacher',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_teacher_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='studyshiftteacher',
            name='study_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.studyshift', verbose_name='Buổi học'),
        ),
        migrations.AddField(
            model_name='studyshiftteacher',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.teacher', verbose_name='Giáo viên'),
        ),
        migrations.AddField(
            model_name='studyshiftteacher',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_teacher_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='studyshiftstudent',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_student_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='studyshiftstudent',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student', verbose_name='Học viên'),
        ),
        migrations.AddField(
            model_name='studyshiftstudent',
            name='study_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.studyshift', verbose_name='Buổi học'),
        ),
        migrations.AddField(
            model_name='studyshiftstudent',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_student_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='studyshift',
            name='class_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classroom', verbose_name='Phòng học'),
        ),
        migrations.AddField(
            model_name='studyshift',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học'),
        ),
        migrations.AddField(
            model_name='studyshift',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_shift_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='studyshift',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='study_shift_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_result_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student', verbose_name='Sinh viên'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='test',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.tests', verbose_name='Bài test'),
        ),
        migrations.AddField(
            model_name='studenttestresult',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='test_result_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='issues',
            name='call_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.studentcare', verbose_name='CSHV gọi'),
        ),
        migrations.AddField(
            model_name='issues',
            name='centre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm'),
        ),
        migrations.AddField(
            model_name='issues',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học'),
        ),
        migrations.AddField(
            model_name='issues',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='issues',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Học viên'),
        ),
        migrations.AddField(
            model_name='issues',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='feedbackteachingquality',
            name='assessment_create_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AddField(
            model_name='feedbackteachingquality',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='feedbackteachingquality',
            name='study_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.studyshift', verbose_name='Buổi học'),
        ),
        migrations.AddField(
            model_name='feedbackteachingquality',
            name='teacher',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='user.Teacher', verbose_name='Giáo viên'),
        ),
        migrations.AddField(
            model_name='feedbackteachingquality',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='courseteacherassessment',
            name='assessment_create_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AddField(
            model_name='courseteacherassessment',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='centre.Course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='courseteacherassessment',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_teacher_ass_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='courseteacherassessment',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_teacher_ass_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='assessment_create_user',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Người đánh giá'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='course',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='centre.Course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='teacher',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='user.Teacher', verbose_name='Giáo viên'),
        ),
        migrations.AddField(
            model_name='coursesurvey',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='survey_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='centre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classroom_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='classesteachers',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học'),
        ),
        migrations.AddField(
            model_name='classesteachers',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_teacher_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='classesteachers',
            name='teacher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.teacher', verbose_name='Giáo viên'),
        ),
        migrations.AddField(
            model_name='classesteachers',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_teacher_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='classesstudents',
            name='classes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học'),
        ),
        migrations.AddField(
            model_name='classesstudents',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_student_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='classesstudents',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='Học viên'),
        ),
        migrations.AddField(
            model_name='classesstudents',
            name='student_debt',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.studentdebt', verbose_name='Công nợ'),
        ),
        migrations.AddField(
            model_name='classesstudents',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_student_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='classes',
            name='centre',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm'),
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.course', verbose_name='Khóa học'),
        ),
        migrations.AddField(
            model_name='classes',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='classes',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.AddField(
            model_name='centre',
            name='created_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centre_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='centre',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='centre_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
    ]
