# Generated by Django 3.1.7 on 2021-03-31 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0002_auto_20210331_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='call_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 9, 57, 51, 749991), verbose_name='Ngày gọi'),
        ),
    ]
