# Generated by Django 3.1.4 on 2021-04-06 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0004_auto_20210331_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='call_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 10, 14, 22, 377621), verbose_name='Ngày gọi'),
        ),
    ]
