# Generated by Django 3.1.4 on 2021-04-06 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0005_auto_20210406_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='call_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 10, 17, 27, 758642), verbose_name='Ngày gọi'),
        ),
    ]
