# Generated by Django 3.1.4 on 2021-04-06 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0008_auto_20210406_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='call_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 6, 11, 38, 9, 817195), verbose_name='Ngày gọi'),
        ),
    ]
