# Generated by Django 3.1.7 on 2021-03-31 09:47

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.password_validation
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default=None, max_length=150, verbose_name='Họ và tên')),
                ('first_name', models.CharField(blank=True, default=None, editable=False, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, default=None, editable=False, max_length=150, null=True)),
                ('username', models.CharField(error_messages={'unique': 'Tên đăng nhập đã được sử dụng'}, help_text='Yêu cầu bắt buộc nhập, chỉ cho phép nhập tối đa 150 ký tự tiếng Anh hoặc ký tự số', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid username.', regex='^[a-zA-Z0-9]*$')], verbose_name='Tên đăng nhập')),
                ('user_code', models.CharField(default=None, editable=False, help_text='Yêu cầu bắt buộc nhập, chỉ cho phép nhập tối đa 10 ký tự tiếng Anh hoặc ký tự số', max_length=10, null=True, unique=True, verbose_name='Mã người dùng')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ.', regex='^\\+?(?:0|84)(?:\\d){9}$')], verbose_name='Phone')),
                ('birth_day', models.DateField(default=None, null=True, verbose_name='Birth Day')),
                ('password', models.CharField(default='pbkdf2_sha256$180000$8LyVdLFJgbEY$gCSdCqLYGy6qAOmMO4l5RkCBs/xLPsqI55RtQFDZhls=', editable=False, help_text='<ul><li>Your password can’t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can’t be a commonly used password.</li><li>Your password can’t be entirely numeric.</li></ul>', max_length=128, validators=[django.contrib.auth.password_validation.validate_password])),
                ('is_superuser', models.BooleanField(default=False, editable=False, verbose_name='Is Super Admin')),
                ('is_staff', models.BooleanField(default=True, editable=False)),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem người dùng này phải được coi là đang hoạt động. Bạn nên bỏ chọn này thay vì xóa tài khoản.', verbose_name='Active')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tham gia')),
                ('last_login', models.DateTimeField(blank=True, editable=False, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('centre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm')),
                ('groups', models.ForeignKey(blank=True, default=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Vai trò')),
                ('user_permissions', models.ManyToManyField(blank=True, default=None, editable=False, help_text='Quyền hạn cụ thể cho người dùng này.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Tài khoản người dùng',
                'verbose_name_plural': 'Tài khoản người dùng',
                'db_table': 'auth_user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Commendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, max_length=255, unique=True, verbose_name='Mã khen thưởng')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('centre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.centre', verbose_name='Trung tâm')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandation_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Khen thưởng',
                'verbose_name_plural': 'Khen thưởng',
                'db_table': 'commendation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'Đang chờ lớp'), (2, 'Đang học'), (3, 'Hoàn thành'), (4, 'Bảo lưu'), (5, 'Mất cam kết'), (6, 'Thanh lý hợp đồng'), (7, 'Rút quyền lợi')], default=None, null=True, verbose_name='Trạng thái')),
                ('academic_power', models.IntegerField(blank=True, choices=[(1, 'Tốt'), (2, 'Khá'), (3, 'Trung bình'), (4, 'Yếu')], default=None, null=True, verbose_name='Lực học')),
                ('parents_phone', models.CharField(blank=True, default=None, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ.', regex='^\\+?(?:0|84)(?:\\d){9}$')], verbose_name='Số ĐT phụ huynh')),
                ('current_company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cơ quan/Trường học hiện tại')),
                ('branch', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chuyên ngành')),
                ('school_year', models.CharField(blank=True, max_length=255, null=True, verbose_name='Niên khóa')),
                ('learning_target', models.TextField(blank=True, max_length=255, null=True, verbose_name='Mục tiêu học')),
                ('learning_purpose', models.TextField(blank=True, max_length=255, null=True, verbose_name='Mục đích học')),
                ('free_to_test', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lịch dự kiến thi')),
                ('free_to_learn', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lịch rảnh')),
                ('how_to_know_odin', models.TextField(blank=True, max_length=255, null=True, verbose_name='Bạn biết odin thông qua kênh nào?')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_user_info_set', to=settings.AUTH_USER_MODEL, verbose_name='Thông tin cá nhân')),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': 'Học viên',
                'db_table': 'student',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Cơ bản'), (2, 'Trung cấp'), (3, 'Nâng cao'), (4, 'Cao cấp')], default=None, null=True, verbose_name='Mức độ')),
                ('test_date', models.DateField(default=None, verbose_name='Ngày diễn ra')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('classes', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.classes', verbose_name='Lớp học')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tests_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Kết quả test',
                'verbose_name_plural': 'Kết quả test',
                'db_table': 'tests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Thông tin cá nhân')),
            ],
            options={
                'verbose_name': 'Giáo viên',
                'verbose_name_plural': 'Giáo viên',
                'db_table': 'teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='care_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Thông tin cá nhân')),
            ],
            options={
                'verbose_name': 'Chăm sóc học viên',
                'verbose_name_plural': 'Chăm sóc học viên',
                'db_table': 'student_care',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StudentCallHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ghi chú')),
                ('call_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Ngày gọi')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('call_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.studentcare', verbose_name='CSHV gọi')),
                ('created_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_call_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student', verbose_name='Sinh viên')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_call_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Lịch sử gọi sinh viên',
                'verbose_name_plural': 'Lịch sử gọi sinh viên',
                'db_table': 'student_call_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptionist_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptionist_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Thông tin cá nhân')),
            ],
            options={
                'verbose_name': 'Lễ tân',
                'verbose_name_plural': 'Lễ tân',
                'db_table': 'receptionist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommendationStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Ghi chú')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('commendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.commendation', verbose_name='Khen thưởng')),
                ('course', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='centre.course', verbose_name='Khóa học')),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comm_student_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('student', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.student', verbose_name='Học viên')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comm_student_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Khen thưởng học viên',
                'verbose_name_plural': 'Khen thưởng học viên',
                'db_table': 'commendation_student',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='commendation',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='user.Student', verbose_name='Danh sách học viên'),
        ),
        migrations.AddField(
            model_name='commendation',
            name='updated_user',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandation_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật'),
        ),
        migrations.CreateModel(
            name='BusinessEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Thông tin cá nhân')),
            ],
            options={
                'verbose_name': 'Nhân viên kinh doanh',
                'verbose_name_plural': 'Nhân viên kinh doanh',
                'db_table': 'business_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authuser_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('created_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_date_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_create_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('updated_user', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_update_user_set', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': True,
            },
        ),
    ]
