# Generated by Django 3.1.7 on 2021-03-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='is_superuser',
            field=models.BooleanField(default=True, verbose_name='Is Super Admin'),
        ),
    ]
