# Generated by Django 3.1.4 on 2021-04-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210331_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Họ và tên'),
        ),
    ]
