# Generated by Django 3.1.4 on 2021-04-06 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0003_auto_20210406_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='groups',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Vai trò'),
        ),
    ]
